name: Publish to NPM

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Build for production
      run: npm run build:production
      
    - name: Run production validation
      run: npm run validate:production
      
    - name: Update package.json version to match tag
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        PACKAGE_VERSION=$(node -p "require('./package.json').version")
        if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
          npm version $TAG_VERSION --no-git-tag-version
          echo "Updated package.json version from $PACKAGE_VERSION to $TAG_VERSION"
        else
          echo "Package.json version $PACKAGE_VERSION already matches tag version $TAG_VERSION"
        fi
      
    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: CNS MCP Server ${{ github.ref }}
        body: |
          ## 🚀 CNS MCP Server Release ${{ github.ref }}
          
          ### Installation
          ```bash
          npm install -g cns-mcp-server@${{ github.ref_name }}
          ```
          
          ### What's Changed
          See [CHANGELOG.md](CHANGELOG.md) for detailed changes.
          
          ### Quick Start
          1. `cns-server init`
          2. Add to Claude Code MCP configuration
          3. Start orchestrating! 🎉
        draft: false
        prerelease: false